// <auto-generated />
using System;
using FezBotRedux.Common.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FezBotRedux.Migrations
{
    [DbContext(typeof(NeoContext))]
    [Migration("20210307061715_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("FezBotRedux.Common.Models.Afk", b =>
                {
                    b.Property<int>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserIdentity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Identity");

                    b.HasIndex("UserIdentity");

                    b.ToTable("Afks");
                });

            modelBuilder.Entity("FezBotRedux.Common.Models.Bet", b =>
                {
                    b.Property<int>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BetName")
                        .HasColumnType("TEXT");

                    b.Property<double>("BetRate")
                        .HasColumnType("REAL");

                    b.Property<int?>("NeoBetIdentity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Identity");

                    b.HasIndex("NeoBetIdentity");

                    b.ToTable("Bet");
                });

            modelBuilder.Entity("FezBotRedux.Common.Models.Blacklist", b =>
                {
                    b.Property<int>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserIdentity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("reason")
                        .HasColumnType("TEXT");

                    b.HasKey("Identity");

                    b.HasIndex("UserIdentity");

                    b.ToTable("Blacklist");
                });

            modelBuilder.Entity("FezBotRedux.Common.Models.DbUser", b =>
                {
                    b.Property<int>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cash")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Identity");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FezBotRedux.Common.Models.Guild", b =>
                {
                    b.Property<int>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefix")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SettingsIdentity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Identity");

                    b.HasIndex("SettingsIdentity");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("FezBotRedux.Common.Models.NeoBet", b =>
                {
                    b.Property<int>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BetName")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("msgID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("open")
                        .HasColumnType("INTEGER");

                    b.HasKey("Identity");

                    b.ToTable("NeoBet");
                });

            modelBuilder.Entity("FezBotRedux.Common.Models.NeoBets", b =>
                {
                    b.Property<int>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BetAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BetLoc")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NeoBetIdentity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserIdentity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Identity");

                    b.HasIndex("NeoBetIdentity");

                    b.HasIndex("UserIdentity");

                    b.ToTable("NeoBets");
                });

            modelBuilder.Entity("FezBotRedux.Common.Models.NeoHub", b =>
                {
                    b.Property<int>("Identitiy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MsgId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Identitiy");

                    b.ToTable("NeoHubSettings");
                });

            modelBuilder.Entity("FezBotRedux.Common.Models.Playing", b =>
                {
                    b.Property<int>("Identitiy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Identitiy");

                    b.ToTable("Playings");
                });

            modelBuilder.Entity("FezBotRedux.Common.Models.Settings", b =>
                {
                    b.Property<int>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlockled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Identity");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("FezBotRedux.Common.Models.Tag", b =>
                {
                    b.Property<int>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GuildIdentity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IfAttachment")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OwnerIdentity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .HasColumnType("TEXT");

                    b.Property<int>("Uses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Identity");

                    b.HasIndex("GuildIdentity");

                    b.HasIndex("OwnerIdentity");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("FezBotRedux.Common.Models.Afk", b =>
                {
                    b.HasOne("FezBotRedux.Common.Models.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserIdentity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FezBotRedux.Common.Models.Bet", b =>
                {
                    b.HasOne("FezBotRedux.Common.Models.NeoBet", null)
                        .WithMany("Bets")
                        .HasForeignKey("NeoBetIdentity");
                });

            modelBuilder.Entity("FezBotRedux.Common.Models.Blacklist", b =>
                {
                    b.HasOne("FezBotRedux.Common.Models.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserIdentity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FezBotRedux.Common.Models.Guild", b =>
                {
                    b.HasOne("FezBotRedux.Common.Models.Settings", "Settings")
                        .WithMany()
                        .HasForeignKey("SettingsIdentity");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("FezBotRedux.Common.Models.NeoBets", b =>
                {
                    b.HasOne("FezBotRedux.Common.Models.NeoBet", null)
                        .WithMany("userBets")
                        .HasForeignKey("NeoBetIdentity");

                    b.HasOne("FezBotRedux.Common.Models.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserIdentity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FezBotRedux.Common.Models.Tag", b =>
                {
                    b.HasOne("FezBotRedux.Common.Models.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildIdentity");

                    b.HasOne("FezBotRedux.Common.Models.DbUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerIdentity");

                    b.Navigation("Guild");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FezBotRedux.Common.Models.NeoBet", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("userBets");
                });
#pragma warning restore 612, 618
        }
    }
}
